name: Linting Checks

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install flake8

    - name: Run Python Linting
      run: |
        source .venv/bin/activate
        flake8 --exit-zero --statistics --count .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run Terraform Format Check
      run: terraform fmt -check